spring:
  application:
    name: sa-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 'http://localhost:4200'
            allowedMethods: GET, POST, PUT, DELETE, OPTIONS
            allowedHeaders: '*'
            allowCredentials: true

security:
  jwt:
    secret:
      key: ZW9KbW8kbUxwU21ybndlKmIzRHNAXm95WmoqQE5qc2R2cnVaQGhmRFZmWFhqQllmall4VVcla0xTUnFGVk5RRw==
    ttlMillis: 604800000
    issuer: Main