spring:
  application:
    name: sa-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
security:
  jwt:
    secret:
      key: ZW9KbW8kbUxwU21ybndlKmIzRHNAXm95WmoqQE5qc2R2cnVaQGhmRFZmWFhqQllmall4VVcla0xTUnFGVk5RRw==
    ttlMillis: 604800000
    issuer: Main